CREATE USER POSTGRESQL_READER_USER WITH PASSWORD POSTGRESQL_READER_PASSWORD;
GRANT CONNECT ON DATABASE POSTGRESQL_DATABASE TO POSTGRESQL_READER_USER;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO POSTGRESQL_READER_USER;
GRANT SELECT ON ALL SEQUENCES IN SCHEMA public TO POSTGRESQL_READER_USER;
GRANT USAGE ON SCHEMA public TO POSTGRESQL_READER_USER;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO POSTGRESQL_READER_USER;