###############
# See parent's docker-compose.yml
##############

# docker-build-db-slave:
# 	docker build -t habitus_habits_db_slave .

# docker-run-db-slave:
# 	docker run -d --name habitus_habits_db_slave -p 5433:5432 --env-file .env habitus_habits_db_slave